[versions]
agp = "8.13.0"
annotation = "1.9.1"
kotlin = "2.0.21"
coreKtx = "1.17.0"
media = "1.7.1"
material = "1.13.0"
superLyricApi = "2.4"
activityCompose = "1.12.3"
composeBom = "2026.01.01"

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
media = { group = "androidx.media", name = "media", version.ref = "media" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
super-lyric-api = { group = "com.github.HChenX", name = "SuperLyricApi", version.ref = "superLyricApi" }
kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }

# Compose
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
material3 = { group = "androidx.compose.material3", name = "material3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

